### ISSUE TITLE
allow efficient data preprocessing in batches of datapoints

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#145]
currently the whole local training dataset is loaded in RAM, as well as the resulting set of preprocessed features. this can lead to memory problems

can we have a more streaming-like preprocessing, where only a small batch of datapoints is loaded and preprocessed in each step?

@steveoni  is investigating some options also, some involving `indexDB`

**Comment by martinjaggi** [comment]
memory problems such as leaks seem to be prevailing with TF.js, hard to fix.  any ideas by others?

**Comment by Nacho114** [comment]
solved by @laurislopata
