### ISSUE TITLE
personalized models

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#146]
summary issue for supporting personalization (both for decentralized and federated)

each task description should include a flag if that task is meant to use or allow personalization.

(for algorithms such as https://github.com/epfml/FeAI/pull/18 but also others )

once the new code structure is settled let's discuss here some more what the easiest code modification would be to allow it 

also needed to later define contribution measures from the perspective of one user

**Comment by dgengler6** [comment]
We started defining that with a Model class that wraps the actual model, it is currently pushed on [epfml/FeAI#18](https://github.com/epfml/FeAI/pull/18). We discussed how to do it this week and we can maybe talk if you think that is is general enough ! :)

**Comment by martinjaggi** [comment]
replaced by #306
