### ISSUE TITLE
docs: update getting started guide for developers

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#147]
https://docs.google.com/document/d/1w2EFiGWPOLw61G5zv8n5NuNQ7bfb6ZkFyp4OLKEdRaE/edit

**Comment by Nacho114** [comment]
- Logic of architecture (how DeAI/FeAI are separated, what is where in case you want to add something, ...)
- Dev procedure (code reviews, branches, ...)

**Comment by s314cy** [comment]
is still #57 still relevant? it mentioned a latex docs file hosted on overleaf
