### ISSUE TITLE
Properly handle disconnected clients

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#171]
Make sure a client properly disconnects. This is currently not the case and can cause training error due to ghost clients preventing the threshold to be reached. 

  

- [x] Server-side, "if we haven't heard from a client, delete him" sort of policy.
- [x] Client-side, properly disconnect from server on tab reload/close.

**Comment by s314cy** [comment]
client-side, this is currently handled by the unmounted Vue hook, yet it doesn't seem to be called when closing the window? I'll investigate once #173 is up and running

**Comment by s314cy** [comment]
I fixed the client-side disconnection process while solving #175. Reloading or closing the app's window now properly disconnects us from server :)

**Comment by martinjaggi** [comment]
thanks! just in case that there might also be 'unplanned' disappearance of some clients, for example if they loose internet connectivity on a phone: does the server also have a time-out to get rid of such clients?

**Comment by s314cy** [comment]
this remains to be implemented (I edited nacho's issue description with a check-list), should be easy, like having a flag for each client and chain-calling setTimeout:
1. call `setTimeout` on client connection
2. on reaching the timeout, either the flag:
- is off, then disconnect the client
- is on, then set it off and call `setTimeout` again

any client request made to the server sets the flag to true, I'll see if this works

**Comment by s314cy** [comment]
I didn't implement this yet, I edited nacho's issue description with a check-list, I've got a good idea as to how to make it work and I'll try to implement it on my working branch for #175  :)

**Comment by Nacho114** [comment]
Client-side, properly disconnect from server on tab reload/close.

-> This should also happen when the user changes to the decentralized setting.
