### ISSUE TITLE
Stop training button

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#175]
(1) Instead of running for a set number of epochs, run until the user presses a "stop training" button.

Solving this issue would also solve the following:
(2) The user should not be able to spam the "train {federated, decentralised}" button. Solving (1) would mean pressing the button again would stop (pause) training.

Further enhancement, requires (1) & (2) beforehand. I'll open another issue if enough people vote for this:
(3) Allow the user to enter their own desired number of training epochs, or a training time limit, through the UI.

**Comment by martinjaggi** [comment]
1,2: perfect. 3: maybe let's postpone. easier for us to think of training of each task going on forever, and users can come and go (so start/stop basically just means join/leave)
