### ISSUE TITLE
Error in training (both in DeAI and FeAI)

### ISSUE THREAD

**Issue by giordano-lucas** [epfml/disco#177]
I get the following error when I press the `train` button.
`Uncaught (in promise) Error: Variable with name dense_Dense1/kernel was already registered`

<img width="1265" alt="Screenshot 2022-01-02 at 15 17 33" src="https://user-images.githubusercontent.com/43466781/147878669-6007f125-ed67-491a-8cd5-edd4ef56d2c9.png">

**Comment by s314cy** [comment]
does it occur on develop or production?

**Comment by giordano-lucas** [comment]
On develop

**Comment by s314cy** [comment]
considering the two PRs merged by @Nacho114, was this issue fixed?

**Comment by s314cy** [comment]
> considering the two PRs merged by @Nacho114, was this issue fixed?

@giordano-lucas @Nacho114 I'm pretty sure everything is back to normal, waiting for your confirmation to close this :)

**Comment by Nacho114** [comment]
Yes, this seems to be fixed now
