### ISSUE TITLE
Model update on late join

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#179]
In case a user joins federated training while round R<sub>T</sub> is still processing, it should ensure it's got the latest available model (provided by the server) on starting R<sub>T+1</sub>. It is currently not checked as the late user does not enter any "wait for weights aggregation" step.

Note that solving this issue would prevent users from joining federated training with their own local model on their first round. If this is something desired, then this issue can be directly closed.

**Comment by Nacho114** [comment]
I think from a theory stand point the best would be to take the model from the server?

But maybe from a practical standpoint people want to start with their own mode, so being able to choose between both would be best?

**Comment by martinjaggi** [comment]
yes both for federated and decentralized, upon joining they should take the
fresh model from the server (or neighbor who started earlier). so it's
actually the same as just a regular training round

starting from a custom own model is less of a priority, can think about it
as a later functionality

**Comment by s314cy** [comment]
thanks for the feedback! I'll follow @martinjaggi's guidelines, i.e. the theory standpoint described by @Nacho114
