### ISSUE TITLE
Display more information on Peer Training console 

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#187]
Display more information on Peer Training console for federated platform

-> E.g. on federated it should say to how many peers you are connected + if you are currently waiting to be selected, etc.

Useful for users to see, and also useful for debugging purposes.

Not sure if this is already modular since the text would depend on if you are on deai or feai, although it shouldn't be hard to implement.

**Comment by martinjaggi** [comment]
yes good idea. we can start with #peers at first. the selected or not is less a prio (in the FL setting the users in general are less in power and don't have much choices, apart from joining or not)

#peers makes perfect sense both in federated and decentralized

**Comment by s314cy** [comment]
yes the code is already modular! and I think this is linked to #157

**Comment by Nacho114** [comment]
This will be tackled by #223
