### ISSUE TITLE
Improving adding data for MNIST

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#189]
Currently for MNIST, you have to add each class separately (e.g. all the 1's in a folder, ... all the 9's). This should be just like for CIFAR where you add images all at once.

**Comment by martinjaggi** [comment]
i guess both are ok modes, the one here is more like an intuitive
'playground' type UI with upload per class. some ML services have a similar
UI i guess.

BTW for CIFAR, we should add a bit more info what kind of format the label
.csv should be. and what file-formats the images are allowed to be
