### ISSUE TITLE
Adding expected input data section

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#190]
Currently in the training frame we give "data examples", but in the case of CIFAR, it's just showing how images look like visually. I added some temporary information of how the data should be formatted (As raised by Martin [in a previous issue](https://github.com/epfml/DeAI/issues/189#issuecomment-1016281176))

This is however important so we should make this section look cleaner.

**Comment by Nacho114** [comment]
This has to be done for all tasks.

**Comment by s314cy** [comment]
@nacho @martinjaggi I suggest we add this important information to either the _Description_ or _Dataset Input_ section.

What would be nice is a preview of an example image against the preview of one of the user's given images, with the required dimensions clearly stated. For CSV datasets, to simply display the expected columns is enough.

**Comment by s314cy** [comment]
done in #389
