### ISSUE TITLE
Task creation loading TensorFlow.js json model file results in null object

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#197]
When loading the TensorFlor.js model in json format for task creation, the object appears to be null.

@giordano-lucas has also tried to debug this: "The error is in the <input type='file'/>  tag  within vee-validate"

**Comment by martinjaggi** [comment]
this was also already solved i think

**Comment by Nacho114** [comment]
No this was not fixed afaik, @s314cy ?

**Comment by martinjaggi** [comment]
can you link the PR in which it was completed?

**Comment by s314cy** [comment]
> can you link the PR in which it was completed?

I regrouped the issues related to the task creation form in #271
