### ISSUE TITLE
FeAI: Network error after epoch 6

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#198]
FeAI: Network error after epoch 6 in federated training:

```Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.```

Found by @laurislopata

**Comment by Nacho114** [comment]
More details on bug: (setup 2 tabs feai on titanic)

This is the output we get before the error on the tab console:

```
EPOCH (6): [training_manager.ts:111](webpack:///src/helpers/training/training_manager.ts?7609)
Awaiting for selection from server...
```

At the same time in the server we have 

```
Checking 4WjGCEfLDI for activity
Client with ID 4WjGCEfLDI asked to get selected
* selected clients:  Set(1) { 's6vKqElhsY' }
* queued clients:  Set(1) { '4WjGCEfLDI' }
=> selected? no
Checking 4WjGCEfLDI for activity
Client with ID 4WjGCEfLDI asked to get selected
* selected clients:  Set(1) { 's6vKqElhsY' }
* queued clients:  Set(1) { '4WjGCEfLDI' }
=> selected? no
Checking 4WjGCEfLDI for activity
Checking 4WjGCEfLDI for activity
```

Basically after the first round, the server puts one user in the selected queue, but keeps the other one in the queued queue, and hence training does not continue.

**Comment by martinjaggi** [comment]
you mentioned this one was resolved probably?

**Comment by Nacho114** [comment]
@s314cy  is working on it, I discussed about this today with him and he has some idea where it's from, should be resolved soon.

**Comment by Nacho114** [comment]
closed since we moved to async and sync is deprecated
