### ISSUE TITLE
simplify client selection in federated mode

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#211]
selection step can be combined with receiving the model

ideally this is a push logic from the server. can we do push already or do we need to wait to have websockets?

also the endpoint names could maybe be made a bit more meaningful, such as
`/weights/[params]` -> `weightsUpdate/[params]` for upload, and different for download? or is the endpoint used for both?

**Comment by s314cy** [comment]
the reason for the current pulling logic, where the client performs regular polling, is the following:

1. for the server to push, it must initiate a http request to the client, which is not always possible (e.g. presence of a NAT)

2. long polling (http communication initiated by client whose request is held by server until resource becomes available and response is sent by server) presents performance issues to the server + does not overcome the 1-request 1-response aspect of http which forces to split the selection and aggregation phases

this is why we should wait for websockets, and thus fully bidirectional communication initiated by client, to move to a pushing logic :)

regarding current endpoints
- `/tasks` provides all tasks metadata
- `/tasks/[task]` provides the model (GET)
- `/weights/[task]/[params]` is the pushing endpoint (POST)

I agree and I would personally go with `/weights/[task]/[params]` being the endpoint for both GET + POST

**Comment by Nacho114** [comment]
deprecated
