### ISSUE TITLE
name change DeAI -> Disco

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#217]
big change :).

we still need to update a few paths, endpoints & deployment scripts

**Comment by Nacho114** [comment]
The name change broke github pages, the main culprit was in:

`mobile-browser-based-version/vue.config.js`, DeAI had to be replaced with disco.

It is not working after the fix.

In general it would be better using our own domain, e.g. disco-platform.com is available at 10usd/yr, then we would not have had this problem. @s314cy , what are other advantages of using our own domain?
