### ISSUE TITLE
Fix model update after end of round 

### ISSUE THREAD

**Issue by dgengler6** [epfml/disco#222]
- Currently the model weights are not updated so basically we are doing local training 
- I did fixed it in my previous iFedAvg PR but it never got merged 
- Error is in _updateLocalModelWithMostRecentServerModel() just fetching the model but never updating it

**Comment by martinjaggi** [comment]
is this for federated or decentralized?

for ifedavg, could you rebase the PR (or merge the current disco into it first?).

given the architecture rapid changes on both sides we're still debating if maybe best to keep it on its own branch for now.

some of the fully personalized modes might be easier to get into disco as they might require less changes, what do you think?

**Comment by dgengler6** [comment]
Only Federated. 

This fix is independent of iFedAvg or personalization, it's just a disco bug. I will fix it here as I already noticed it when I was working on my branch :) 

We discussed maybe keeping iFedAvg in the experimental branch on Friday. So no rush for merging it rn.

**Comment by martinjaggi** [comment]
ok very nice. can you make a separate PR for this bug then?

**Comment by dgengler6** [comment]
Sure thing, that's the plan !

**Comment by martinjaggi** [comment]
this has been resolved by @dgengler6 and @Nacho114 in #242 i think. did you do a test run after the fix?

**Comment by Nacho114** [comment]
I think @dgengler6 manually tested it. Will add this as a proper test after we do an end 2 end test.
