### ISSUE TITLE
Simple peer

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#224]
For decentralised we currently use peerjs, as noted by @giordano-lucas, this has two issues:

- It is no longer maintained.
- It needs browser integration.

Both are problematic, due to the latter this means we can have 0 automatic tests. Since decentralised is an important part of the platform it is worth using a solid api for it.

**Comment by martinjaggi** [comment]
what are the main differences between peerjs and simple peer?

**Comment by Nacho114** [comment]
- The main difference is that simple peer allows us to run with nodejs and no browser ( allows to to unit test decentralized ).
- simple peer seems to be more up to date with webRTC specifications (more up to date, but this I found in a post that is perhaps a bit dated now).
