### ISSUE TITLE
Server communication HTTP vs Web sockets

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#226]
Server communication HTTP vs Web sockets

Should we keep HTTP or move to Web sockets?

The benefit of Web sockets is that we can easily push data from server to client, e.g. "model update" or even for hyper parameter tuning #151. These features are more complex with HTTP.

The problems with web sockets are mainly the overhead it adds, although this might be negligible?

Work wise it is worth it given the benefits that we mentioned.  

Some reading:

https://blogs.windows.com/windowsdeveloper/2016/03/14/when-to-use-a-http-call-instead-of-a-websocket-or-http-2-0/

**Comment by martinjaggi** [comment]
this has been done by @tharvik i think, so we can close this?

**Comment by s314cy** [comment]
> this has been done by @tharvik i think, so we can close this?

only for decentralized, federated still lacks ws

**Comment by s314cy** [comment]
@martinjaggi if @tharvik confirms i will be reopen the issue

**Comment by tharvik** [comment]
Right, federated doesn't use websocket yet
