### ISSUE TITLE
Remove dynamic route building of tasks to simplify web app.

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#232]
**Is your feature request related to a problem? Please describe.**

When you are in a task related frame (e.g. training frame) you cannot reload the page (if you do it goes into page not found state); this is due to these pages being built dynamically which also increases the complexity of the app. 

**Describe the solution you'd like**

Remove the dynamic route building and keep it static and single paged, simply keep track of what the current chosen task is in the store.

**Comment by martinjaggi** [comment]
ok, but keep in mind that we might like to allow joining several tasks in the long term

**Comment by s314cy** [comment]
closed by #322
