### ISSUE TITLE
Test core of disco

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#237]
Test the core of disco:

- Train data
- [ ] Check hyper parameters are being correctly set
- [x] Fractional round callbacks

- Client
- [ ] When new model is available, check that weights are fetched 
- [ ] When new model is available, check that weights are updated
- [x] Fetch current round

- Server
- [x] API test (GET, PUT, ...)

**Comment by s314cy** [comment]
this will be progressively implemented over time, no need for a specific issue
