### ISSUE TITLE
Fetch weights from buffer and not the initial model when updating the model

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#238]
**Describe the bug**
We mistakenly thought createModel was updating the weights, it fetches the initial model. We need to fetch the latest weights from the buffer.

**Comment by Nacho114** [comment]
Upon close inspection this is wrong, if we trace `_aggregateAndStoreWeights` in the `request_handlers.ts` we are storing weights where we fetch them, the only issue is the bad name of the function used to fetch, i.e. task.createModel...

**Comment by martinjaggi** [comment]
let's properly name the function then

**Comment by Nacho114** [comment]
Note -> For this issue it's more than renaming the function, question of:

Do we always just fetch the latest mode vs do we also want to fetch some sort of initial model (maybe we want to try alone etc). If not, then we can just rename, otherwise we need have to different function calls.

**Comment by martinjaggi** [comment]
this class is for FL, so should be clear for that and only that (local training doesn't need to be here, as it's unified for both FL and decentralized) 

TODO: rename here so logic makes sense, and also explain in the comments in this file how it interacts with `_aggregateAndStoreWeights` in `request_handlers.ts`
