### ISSUE TITLE
Make server url calls consistent

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#253]
As noted by @s314cy, the `serverUrl` usage is not consistent, sometimes passed as an argument, sometimes hard coded.  In the `decentralized_client` it is being chosen inside the constructor which does not make much sense (this part will probably be fixed by @tharvik in his upcoming PR). 

We should think about a clean way to use it (e.g. a dedicated class that is tasked to choose the appropriate url, this object is then passed to the client, or something along these lines).  

- [ ] Rename `VUE_APP_FEAI_SERVER` to something else, e.g. `VUE_APP_FEDERATED_ENDPOINT` 
- [ ] Rename `VUE_APP_DEAI_SERVER` to something else, e.g. `VUE_APP_DECEENTRALIZED_ENDPOINT`
- [ ] The naming of the previous two should be consistent.
- [ ] Move functions in `src/core/task/utils.ts` that do server calls to the communication folder, rename it to communication.ts
- [ ] Change `tf.loadLayersModel(process.env.VUE_APP_FEAI_SERVER.concat(`tasks/${taskID}/model.json`))` to use axios instead, this way we can centralize the server url endpoint. 
- [ ] Remove `process.env.VUE_APP_FEAI_SERVER` usage, and set it up in the axios config.

**Comment by s314cy** [comment]
pretty sure this has been solved? @Nacho114
