### ISSUE TITLE
Replace lodash with immutable map functionality  

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#259]
@tharvik introduced [immutable](https://immutable-js.com/) that adds immutable collections to js, it also adds maps, filters, ... these are more comprehensible than the current maps we use via `lodash`. 

- Replace the remaining `lodash` usage from the code with the corresponding `immutable` and then remove `lodash` from the packages.

**Comment by s314cy** [comment]
@tharvik seems to still be working on this when going through the code and adding his own features

I'll try and do the same, instead of directly pushing for "immutable everything" within a single PR
