### ISSUE TITLE
Simplifying the Platform usage

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#262]
Due to the merge of DeAI and FeAI, the specification of platform is a bit convoluted. We currently choose the platform via the side-bar and this is stored in the `store`. At the end we should just choose the training type at the very end, i.e. in the trainingFrame, there is no reason to store the platform in the store. As a side note, we when doing this, in the training manager there is a separate flag for training alone, but this could be integrated with the platform so that there are 3 types, the 2 original + local (train alone).

**Comment by martinjaggi** [comment]
all platform selection has been removed, right? (it's only stored on the task)

so i suppose we can close this?

**Comment by s314cy** [comment]
> all platform selection has been removed, right? (it's only stored on the task)
> 
> so i suppose we can close this?

I'm not sure @dgengler6 was able to merge his work yet?
