### ISSUE TITLE
README for users (non developers)

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#263]
As a reminder the disco structure will soon look as follows:

Disco/
   - DiscoJS/
   - Server/
   - Browser/
   
Currently mobile-.../ (which contains all the main code) has good readme, but it's made for developers. At the root of disco there is a readme, but it is a broad introduction.

We need to include a README for users (non developers), and this should be the first thing you see after the overview.

One idea is the following, at the root, the README should have:

- Brief overview (what we have now but reduced)
- Section for users (brief overview) -> then it links to a HOW_TO.md with more detailed info for users
- Section for developer (brief overview) -> then links to our current readme for devs

In the root we also have the guide of how to contribute to disco, and a brief overview of the structure (we have these already just need to change where they are).

Then in DiscoJS/, Server/, ... the readme will be for developers (what we have now).

**Comment by martinjaggi** [comment]
quick check again if users understand the main functionalities. maybe @aunell @Grim-bot could also cross-check, before we release the first version?

**Comment by martinjaggi** [comment]
partially addressed in PR #331

**Comment by martinjaggi** [comment]
done in #483 and some earlier ones
