### ISSUE TITLE
fix the task creation form

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#271]
need to repair the [task-creation-form](https://epfml.github.io/disco/#/task-creation-form)

- [ ] add task type (decentralized, federated, personalize) as a dropdown selection to the task definition
- [ ] check functionality again now with recent backend changes
- [ ] provide default values for most fields if possible (#209)
- [ ] fix upload of model.json file (#197)

**Comment by s314cy** [comment]
Includes fixing #197

**Comment by martinjaggi** [comment]
added one item to also have the task type (decentralized, federated, personalized) selected as a dropdown selection to the task definition

**Comment by martinjaggi** [comment]
is this done? (also existing tasks that the user visually understands if they are decentralized or federated?)

**Comment by Nacho114** [comment]
No, we pushed it further in the todo list in one of the previous friday meetings. we can work on this next.

**Comment by martinjaggi** [comment]
will fix only later, 
but we'll show the current form again for info, with a warning message on top of it
