### ISSUE TITLE
Translation : Write all the texts of the app in the I18n file

### ISSUE THREAD

**Issue by dgengler6** [epfml/disco#275]
**What should be done ?**
Basically, we want to migrate all hardcoded texts of the platform to `src/locales/content/default.json` which is the default locale in english. 

**Why is this useful ?**
If we ever want to add languages support to disco, this is really important, once it is done, one could copy default.json in say french.json and write translation for the whole platform.

Labelled for later because this is quite tedious but it's a good practice that we should keep.

**Comment by Nacho114** [comment]
Will be an ongoing process, better to have less issues.

**Comment by martinjaggi** [comment]
want to add it to the long term project?
