### ISSUE TITLE
In tfjs, using generators does not initilize the size variable -> round tracker not working -> federated not working

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#279]
In the latest PR we use the tfjs Dataset object, using the generator allows lazy loading which is excellent as this allows to load data sets without having to worry about size.

However `dataset.size = null` since this is the default value of the tfjfs datset object and it is not initialized (in the tfjs code). 

To understand what is going on note that (in the `image_loader.ts`), the generator is built via an iterator, the corresponding tfjs code is [here](https://github.com/tensorflow/tfjs/blob/tfjs-v3.13.0/tfjs-data/src/readers.ts#L201-L207), this will then call [datasetFromIteratorFn](https://github.com/tensorflow/tfjs/blob/e0ea5a744aa421b0b6930e2dfbe59795e6225807/tfjs-data/src/dataset.ts#L546), it sadly passes no size argument, so the size is never defined.

The train size is important since we need this to keep track of the latest round in the `RoundTracker`. 

Ideally we would call `datasetFromIteratorFn`, since can pass our built iterator along with the size, however this is function is not exported in the index.d.ts tfjs.

@s314cy what do you think?

As a brief workaround I will wrap the tfjs dataset class inside our own dataset class.

**Comment by martinjaggi** [comment]
no, the train size is irrelevant for rounds. so federated & decentralized really should work already

round needs to be specified direclty as a number of batches (irrespective of epoch or data size). it already is like this, but maybe the computation now is a bit a detour

the system should work fine in the case of infinite training data (both federated and decentralized).

**Comment by Nacho114** [comment]
Since we defined a round in units of epochs, we need to know the train size. If we define it in terms of batches, the of course it's irrelevant. Because of this, federated does not work right now

**Comment by Nacho114** [comment]
ill add an issue for this since it seems like an important question

**Comment by Nacho114** [comment]
As a side note, when we move to rounds being in batches, indeed train size will not matter.

However it might be a useful thing to have, so perhaps it is worth to keep the changes i added in the last PR, @s314cy, adding a wrapper to the dataset to include size info (i sent u some more info on this).

**Comment by martinjaggi** [comment]
yes, please redefine in terms of batches, it will make all easier (we had
the same small issue in the past but it keeps popping up)
