### ISSUE TITLE
RoundDuration measure: switch from epochs to batches

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#281]
RoundDuration measure: switch from epochs to batches

Batches is a more natural measure for round duration. This way all clients have the same frequency of communication (if it's in terms of epochs it depends on their data size).

TODO: do these changes in the `RoundTracker`

----

What is the right measure for the round duration?

Right now it's in epochs, that means if roundDuration = .5, then every half epoch we communicate.

We could do batches instead, and say, every X batches we communicate, but in this case we need to take into account the batchSize.

I guess ideally a round of communication corresponds to a fixed amount of computation? I have not read / looked into this question.

**Comment by martinjaggi** [comment]
let's switch to batches, as we already discussed. indeed that will satisfy all desired properties such as fixed computation (and is also more intuitive for the task config for the user).

who can make a small PR?

**Comment by Nacho114** [comment]
but is it not important to take into account the batchSize? (if it's small then we will be communicating much more often), although I guess this in turn depends on size of data / model.

**Comment by Nacho114** [comment]
so I guess batches is ok as a rough approximation in that case since being accurate about all this would be a huge ordeal.

**Comment by martinjaggi** [comment]
#batches defines round
#batches*batchSize defines computational effort

all fine
