### ISSUE TITLE
Shuffle data

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#288]
Add default shuffle (either to dataset or .fitDataset); if the data is not shuffled we saw some strange oscillatory behavior during early training.

**Comment by s314cy** [comment]
Using the native `shuffle` method of `Dataset` objects does not solve the accuracy issue encountered when training the "simple face" task. Instead a custom shuffle function instead seems to solve the issue.

**Comment by Nacho114** [comment]
dusplicate issue

**Comment by martinjaggi** [comment]
#294

**Comment by martinjaggi** [comment]
you might need to keep the number of local steps (per round) quite small.
and/or make sure each class is available on each of the two clients say
