### ISSUE TITLE
Add validation and data shuffle 

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#294]
Need to add data validation and shuffling to the data loader. (only inside each local client data, not between clients that is)

- [x] Update the return type of `load` to `Promise<Data>`
- [x] Add shuffle and seed mechanism (the `TFJS` version seemed to be broken, might be worth to test it again though)
- [ ] Add validation dataset, there is a validationSplit number param, but it does not seem to be supported on the current `TFJS` version we have. So either update `TFJS` and try it out, or do a split manually in the data loader, and add corresponding dataSplit param in builder.

**Comment by Nacho114** [comment]
To avoid things breaking it's best to be conservative for now, and just add the easier solution for validation set, and we can in a later point try to update `tfjs`

**Comment by Nacho114** [comment]
data shuffling is only done locally (not between clients)

**Comment by s314cy** [comment]
#338 indirectly depends on this

**Comment by martinjaggi** [comment]
did you guys check what's currently shown on the validation plot during training? if there is an issue we can remove it temporarily (discussed with hugo)

**Comment by s314cy** [comment]
#356 adds shuffling

**Comment by s314cy** [comment]
#372 adds validation split for image datasets

**Comment by martinjaggi** [comment]
done i guess in #356 and #499
