### ISSUE TITLE
Add differential privacy 

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#303]
![image (1)](https://user-images.githubusercontent.com/17376073/165946414-946a6c4f-81de-4ee8-88ef-ff54f9761160.png)

**Comment by martinjaggi** [comment]
actually it's the line after add noise (and the clipping is good also). the rest we don't need, so can keep unchanged from current decentralized/federated as we have it

**Comment by s314cy** [comment]
Solved by #320
