### ISSUE TITLE
Testing page

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#314]
The testing page is not working at the moment.

While fixing it, one should come up with clear/intuitive rules about what model can be tested (working models? saved models? what about working models currently being trained? etc.)

**Comment by martinjaggi** [comment]
yes by default it should just use the current working model. it doesn't even matter if it's still training or not.

more fancy option can be to offer a model selection switch.

the same testing page should also be reached from the model library, if clicking on a particular model and want to play with it.

#315 helps simplifying this too.
