### ISSUE TITLE
Wrapping up the essentials

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#316]
Before discussing further features I think we should conclude the "essentials"

If I understood right they are the following:

The core of disco would be:

- Data loaders (80% done)
- Model Training (Done)
- Federated (Done)
- Decentralized (Done)
- Model Testing (0%)

The data loaders need:
- Validation splits 
- Shuffling (native TFJS option seemed buggy due, perhaps due to images being load lazily)

Non-trivial since we support different data loaders.

Model testing

- I have not at all looked at the state of this. (We were always working on the training / federated aspect).

Bonus:
- Have a nice model to visualize, titanic just has constant training acc at .6, does not look so good.

**Comment by martinjaggi** [comment]
**validation split:** yes, need that (could actually call it test for simplicity). the size is specified already in the task description i think. this functionality is already working fine i think
- [ ] change valid -> test naming

**shuffling:** we don't really need it. this can be done outside disco, before connecting the file. anyway most crucial shuffling or not is the one between agents, which clearly is outside disco. within one client, it matters less. also it can be shuffled before being connected to disco, so don't strictly need disco code for this. it's the same situation as for larger preprocessing steps which can't be done online. they are outside scope for disco, and users can easily do those in python / their favorite _offline_ tool, before shipping data to disco

so i think only the testing page remains an issue (separate issue #314)

**Comment by Nacho114** [comment]
validation split: It used to, but with the changes from Hugo we did not add this yet. I think the shuffling would have been the tricker part. Still, it's something we need to add, I think I told him to skip it to get everything working asap at the time.
