### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by tharvik** [epfml/disco#332]
- [x] create NPM organisation
- [x] rename `discojs` to `@[NPM-org]/discojs` in package.json and deps using it
- [x] improve readme to explain API
  - [x] add a few line on the Node API @tharvik 
- [x] test and merge https://github.com/epfml/disco/pull/333
- [x] push develop to production
- [x] tag as `v1.0.0` production's HEAD

**Comment by Nacho114** [comment]
Very nice; Might also be able to add the testing frame @s314cy is working on!

**Comment by Nacho114** [comment]
It would also be good to add documentation of how to use discojs via npm in the discojs readme.

**Comment by s314cy** [comment]
> Very nice; Might also be able to add the testing frame @s314cy is working on!

if i understand correctly, the npm package will only include discojs and not the browser

**Comment by s314cy** [comment]
btw, do we agree on version 1.0.0 and not 0.1.0? since the package has never been used publicly, i would go for 0.1.0

**Comment by Nacho114** [comment]
The v1 is for the github version tag, so it includes the browser.

0.1.0 sounds good to me

**Comment by s314cy** [comment]
> The v1 is for the github version tag, so it includes the browser.
> 
> 1.0.0 sounds good to me

how does the npm release version relate to the version used for the github release? how would we manage the server's docker image version then?

**Comment by tharvik** [comment]
Published on NPM as v1.0.0: https://www.npmjs.com/package/@epfml/discojs :partying_face:
