### ISSUE TITLE
Dark theme compatibility

### ISSUE THREAD

**Issue by gozgun** [epfml/disco#346]
When a user chooses dark theme some texts become invisible. Image background colors and text colors needs to be compatible with the theme change.

**Comment by martinjaggi** [comment]
we can keep the issue for later, 

it would be nice to get the dark theme working again in the next version

**Comment by gozgun** [comment]
I closed it since Hugo opened one (#345) that covers the issues with the dark theme.

**Comment by s314cy** [comment]
i think we want to both deal with the issues reported in #345 AND provide a dark theme, dealing with the former will even help for the latter :)

**Comment by JulienVig** [comment]
@tomasoignons is this issue still relevant?

**Comment by tomasoignons** [comment]
I don't think so, I made sure all the texts were visible when I added the new dark theme feature.
