### ISSUE TITLE
Browser UI compatible with mobile

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#349]
The current browser UI was designed for 13 inches and above screens. On mobile, while the UI is displayed fine in most places, it is far from ideal and some pages are simply not shown correctly at all. Hence, it should get a mobile version revamp.

**Comment by martinjaggi** [comment]
in a first step let's just fix the homepage 3 boxes. everything else looks quite ok on a phone already

**Comment by s314cy** [comment]
#350 fixed most of the text boxes being "squeezed" (and thus made unreadable) on mobile

the last remaining piece of design to rework are the various progress bars displayed throughout the app
