### ISSUE TITLE
Explain DISCO abbreviation on homepage

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#357]
PROBLEM: It is not clear to outsiders why the platform is called "DISCO"

SOLUTION: Add colour coded text to the home page under the logo: "(DIS)tributed (CO)llaborative learning platform"
--DIS and CO should be bold in the logo font and colour-matched to the logo.

**Comment by martinjaggi** [comment]
yes, let's surely add this as the first thing on top of the information page? https://epfml.github.io/disco/#/information
