### ISSUE TITLE
Persistent models server-side

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#363]
With the server now being compatible with both the browser and Node, there are issues with the TFJS backend which prevent the server from storing its trained models to disk, thus any server reboot/crash would mean a loss of the trained models. This also means the trained models are not reusable by the entity hosting the server other than by manually fetching the model over HTTP.

**Comment by martinjaggi** [comment]
yes, but this is not a huge immediate problem as models are still properly saved on the clients, which is the main value for our users
