### ISSUE TITLE
Fix link in README

### ISSUE THREAD

**Issue by liabifano** [epfml/disco#369]
The develop guide link redirects to: https://github.com/epfml/DEV.md
It should be: https://github.com/epfml/disco/blob/develop/DEV.md

I didn't submit the change because I don't think I have permission.

**Comment by Nacho114** [comment]
let me know if u want to contribute, in that case I can give you permission.

I had a look at https://github.com/epfml/disco/edit/develop/README.md, 3 times there is a link to DEV.md, they are all the same (if you look at the source code: `[developer guide](DEV.md)`), for some reason the last one is not working. Strange.

**Comment by martinjaggi** [comment]
thanks to both of you!

BTW in terms of permissions, isn't anyone allowed to make a PR?

**Comment by Nacho114** [comment]
I think anyone can make a PR to a public project, however if you don't have write access then you need to do this on a fork of the project.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

"If you want to create a new branch for your pull request and do not have write permissions to the repository, you can fork the repository first. For more information, see "[Creating a pull request from a fork](https://docs.github.com/en/articles/creating-a-pull-request-from-a-fork)" and "[About forks](https://docs.github.com/en/articles/about-forks)." "
