### ISSUE TITLE
Explain DISCO name on homepage

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#376]
First time users still don't immediately understand what DISCO stands for.

How about something like this :
![Screenshot 2022-07-14 at 00 08 47](https://user-images.githubusercontent.com/62021543/178845342-b5e07dbb-7950-4649-bb2b-bccfb74b5000.png)

**Comment by martinjaggi** [comment]
done in #373

**Comment by Annie-LiGHT** [comment]
but...it currently does not appear on the homepage at all (which is why I reposted the issue)

**Comment by s314cy** [comment]
> but...it currently does not appear on the homepage at all (which is why I reposted the issue)

right, I thought we wanted it on top of the information page only, maybe we can reopen it then?

**Comment by martinjaggi** [comment]
sorry i missed that there were 2 issues
