### ISSUE TITLE
Add data harmonization step

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#377]
We assume that the user harmonizes their data to the expected format.
However no specific guidance is given on this task. 

SUGGESTIONS: 
1) Add a dedicated "Harmonize Your Data" step with instructions 
![Screenshot 2022-07-14 at 00 48 49](https://user-images.githubusercontent.com/62021543/178850074-d233b797-617c-4122-9599-4801925daa64.png)

2) Add harmonization instructions in the Task description (second choice as that would create a lot of text on a single page)
![Screenshot 2022-07-14 at 00 49 01](https://user-images.githubusercontent.com/62021543/178850079-366b1968-145a-4b69-943d-5a610263de2d.png)

**Comment by martinjaggi** [comment]
yes this is important, to allow checks of user's data early on and guide them.

i'd suggest to keep it as part of the `Connect your data` for now. Can we add checks there (for example that there are never any NaN losses on a datapoint say) and offer the help link as suggested by annie?

**Comment by martinjaggi** [comment]
related to #100 and some other checks mentioned there

**Comment by Annie-LiGHT** [comment]
Agreed-- putting this in the `Connect your data` tab is more efficient.
Maybe it could appear as a warning with a link like below or similar
![Screenshot 2022-07-14 at 13 41 11](https://user-images.githubusercontent.com/62021543/178974667-7a155575-c890-4b56-a0a7-2e4bb5814f3c.png)
:
