### ISSUE TITLE
"I.URL is not a constructor" error

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#378]
Error when "train collaboratively" is requested in LUS-COVID task

![Screenshot 2022-07-14 at 00 54 15](https://user-images.githubusercontent.com/62021543/178851584-8e98434e-df20-4e55-b256-124fee95531b.png)

**Comment by Nacho114** [comment]
This issue is related to decentralized only. Should be addressed after #351 is fixed.
