### ISSUE TITLE
ReRefactor into a single package/module?

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#384]
Refactoring the original code was very good since this has allowed to have a pure js version of disco (so we are able to run tests and now CLI).

However, we have multiple folders (server, discojs, and soon benchmark), each of which has it's on node_modules/ that give a non-trivial overhead in terms of memory, but also multiple configs to manage.

It might be a good idea to merge all of these (i.e. put the server and benchmark code into discojs). 

The drawback is that clients would have a bit of server code, but at the moment the server code is minimal so it's a low overhead and it does reduce the project complexity which is big gain.

**Comment by s314cy** [comment]
@tharvik @martinjaggi wdyt?

**Comment by martinjaggi** [comment]
yes i would be supportive of this. have briefly chatted with nachos. 

it would reduce complexity quite a bit and also the install problems we sometimes had (ordering of installs was often a source of bugs?). wdyt?

**Comment by martinjaggi** [comment]
after discussing, we think it's better to keep things separate, as it is now. a package should contain at most one of `tf node` and `tf browser`
