### ISSUE TITLE
DataLoader File Consolidation

### ISSUE THREAD

**Issue by aunell** [epfml/disco#393]
Currently, dataloaders are created for different tasks in different spaces in the code. We need to consolidate this so that each task has its own dataloader.

**Comment by s314cy** [comment]
Currently, the `discojs` package aims to be environment (browser/Node) independent.

In the case of data loaders, the abstract `readImageFrom` and `readTabularDatasetFrom` methods of the abstract `ImageLoader` and `TabularLoader` classes, respectively, must be defined by either the Disco client (browser env) or any user importing `discojs` to their project (either browser or Node env).

As of now, the only definitions of the two methods are offered by the `Web{Image, Tabular}Loader` subclasses in `browser`, and the `Node{Image, Tabular}Loader` subclasses in the tests of `discojs`. The definitions in `browser` are clearly located in `src/data_loader.ts`, whereas I agree that the definitions in the tests of `discojs` deserve better.

An asset of these data loaders is that they need not be redefined for every single task of Disco, so I don't really see the advantage of redefining them for each task. All the tasks need to define is a few parameters required for both training and loading the data (almost simultaneously). I think we should reuse this concept for potential preprocessing functions: tasks would specify a list of such functions that Disco would predefine.

**Comment by martinjaggi** [comment]
ok you have good points.

still, we should try to avoid as much duplication as possible between browser,node/benchmark .  

in benchmark there is still code for every task in some of these subpackages: https://github.com/epfml/disco/blob/develop/benchmark/src/data.ts  
so i was thinking that kind could rather be in discojs so it can be used by both browser and node?

for preprocessing, nothing new needed yet, but i think it would be a great idea to at least add an empty boilerplate function (and comment) in the individual task .ts files, just to tell users where they  _could_ put additional task-specific preprocessing, if needed. the interface for it would be simple, as we already have the batch-wise preproc architecture anyway
