### ISSUE TITLE
Navigation in TEST does not match TRAIN

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#397]
- Navigation bar in [testing panel ](https://epfml.github.io/disco/#/testing) not clickable.
- Left and right arrows should be changed to `PREVIOUS` `NEXT` (to match navigation in training step)

**Comment by s314cy** [comment]
Do we prefer the navigation arrows or text buttons?

Also, the bar isn't clickable in training either; only the information page has a clickable navigation bar. Do we want all bars to be clickable?

**Comment by Annie-LiGHT** [comment]
I'm a button fan. (I think the arrows will go wonky on mobile)

Yeah I see the the navigation buttons aren't clickable now...would be great if they were...(text and icon)

**Comment by martinjaggi** [comment]
yes currently there are 3 different kinds of progression bars. let's just use one of them consistently (and yes text&icon should be clickable too)

no strong preference for arrows or prev/next buttons, but let's be consistent (and make them prominent enough so people never miss the ability)

**Comment by s314cy** [comment]
forgot to make the icons clickable, reopening this accordingly
