### ISSUE TITLE
Server deployment fails

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#416]
the GitHub workflow managing server deployment fails https://github.com/epfml/disco/actions/runs/2748310505

**Comment by s314cy** [comment]
It seems the error comes from the MobileNet model downloaded by CIFAR10 with `node-fetch` rather than the vanilla `fetch`, following the TF.js backend changes brought by #391. Indeed, `tf.loadLayersModel(...)` is now called within Node and thus uses `node-fetch` under the hood.

No idea why `node-fetch` fails, though. Maybe different default timeouts?

**Comment by s314cy** [comment]
A quick fix would be to use another model than MobileNet for now.

**Comment by Nacho114** [comment]
There is some more info [here](https://www.tensorflow.org/js/guide/save_load#native_file_system_nodejs_only):

"Note: This implementation relies on the presence of the [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) method, if you are in an environment that does not provide the [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) method natively you can provide a global method names fetch that satisfies that interface or use a library like (node-fetch)[https://www.npmjs.com/package/node-fetch]."

Might be possible to change the default fetch method called. Although it would be good to understand why `fetch-node` is failing in the first place.
