### ISSUE TITLE
Network error in `train collaboratively`

### ISSUE THREAD

**Issue by ineiti** [epfml/disco#433]
**Describe the bug**
In the child/adult model, when pressing `Train collaboratively`, after some time I see a `Network error` message, and the two accuracy-figures go to 0.

**To Reproduce**
1. Join `Simple Face`
2. Add 4 images each
3. Chose `Train collaboratively`

**Expected behavior**
Finish training

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: Chrome

**Comment by Nacho114** [comment]
Looks like this was in the live version; I went through the server logs and found the following error:

```[error] 33#33: *34193 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.217.168.84, server: , request: "GET /feai/round/simple_face/46d210e9-fb87-4379-be31-10fc2a1caf0a HTTP/1.1", upstream: "http://172.17.0.1:8080/feai/round/simple_face/46d210e9-fb87-4379-be31-10fc2a1caf0a", host: "deai-313515.ew.r.appspot.com", referrer: "https://epfml.github.io/"```

Although it looks like after this event weights were still being pushed, so it might not be what broke it.

Currently trying to reproduce (though it looks like the live server is down?) -- Recent changes caused an issue with deploy server #416. Will try to change the model that causing trouble and redeploy to master to update the live server as this might fix it.

**Comment by Nacho114** [comment]
This needs to be checked again once #416 is fixed as it might be related. Currently being being fixed [here](https://github.com/epfml/disco/pull/436)

**Comment by ineiti** [comment]
Today I tried again and I had two errors:

- Network error

then I tried to re-run, which went OK until round 49, then it stopped (is that normal?).

Then I re-ran it again and got another error.

The logs are attached

[epfml.github.io-1659680605971.log](https://github.com/epfml/disco/files/9265940/epfml.github.io-1659680605971.log)
