### ISSUE TITLE
Show short summary when on mobile

### ISSUE THREAD

**Issue by ineiti** [epfml/disco#437]
**Is your feature request related to a problem? Please describe.**
The project cannot be opened on a mobile device.

**Describe the solution you'd like**
Show at least a short description and why it doesn't work.

**Describe alternatives you've considered**
Making it work on mobile - but that might be difficult.

https://twitter.com/m_gn_s/status/1555136650598141953

**Comment by martinjaggi** [comment]
can you try again now? you caught it 1min during a deploy when the app wasn't up

it should definitely work on mobile, that's our main focus

**Comment by Nacho114** [comment]
It works on mobile, when he opened the link the project was being re-deployed so the site was briefly down
