### ISSUE TITLE
Onboarding document

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#458]
While the DEV.md gives some hints as how to get started and where some things can be found, it is not very beginner friendly; a new student would struggle with it.

I will start working on an *On boarding* document intended for both students and new engineers in order to help them get started, going step by step into what is important depending on what they work on. It will link to other guides we have already written, so it would basically serve as an entry point of truth. (Perhaps we can merge it with DEV.md)

**Comment by s314cy** [comment]
@Nacho114 confirmed to me that the issue is done 👍 (PR #459)
