### ISSUE TITLE
Update README guides

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#487]
This readme is out of date: https://github.com/epfml/disco/blob/develop/information/TASK.md as noted by Dennis Yurkevich

**Comment by s314cy** [comment]
I'll go further and say we need to review/update all docs again, especially the DEV/discojs-core/discojs/discojs-node README's. They should go in greater details on how to interact with the lib in general, not only the training part (e.g. how to get training stats, how to validate/test a model, etc.).

**Comment by martinjaggi** [comment]
yes we can start from what we have, but indeed could be nice to give some example-based guides on how to build stuff on top of disco - always keeping the audience in mind from their needs, that is to build sth impressive quickly and easily. our own code structure is less important in general, just a means for the first thing. anyway, we have some good base and can improve step by step

**Comment by s314cy** [comment]
> yes we can start from what we have, but indeed could be nice to give some example-based guides on how to build stuff on top of disco - always keeping the audience in mind from their needs, that is to build sth impressive quickly and easily. our own code structure is less important in general, just a means for the first thing. anyway, we have some good base and can improve step by step

I completely agree. I thought of making Markdown guides containing code samples of a few lines along explanations — what's expected by the code & what it outputs — similar to what a Jupyter notebook might look like (e.g. in the style of [this existing guide](https://github.com/epfml/disco/blob/develop/information/TASK.md))
