### ISSUE TITLE
Select image data and provide labels as .csv

### ISSUE THREAD

**Issue by s314cy** [epfml/disco#496]
## Feature

In the web client, training a model with image data requires the user to select the images every time for every label, which can quickly get cumbersome. A user should be able to provide all the images at once, along with a single .csv file containing all the image file names mapped to their corresponding label.

## Specifications
A user would provide a single .csv file with lines of the following format: `image_file_name.png, label`

**Comment by francesco98** [comment]
I can work on it. 

I will add the following dependencies to read CSV file:

```
npm i d3
npm i @types/d3
```

**Comment by francesco98** [comment]
Closed by https://github.com/epfml/disco/pull/513
