### ISSUE TITLE
Duplicate text (COVID LUS task)

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#505]
![Screenshot 2022-10-26 at 15 17 36](https://user-images.githubusercontent.com/62021543/198036040-e2a8493d-b9bb-4ed7-b1c2-88466df1d6ef.png)

**Comment by s314cy** [comment]
this is the same issue as in #478, so either someone's rebase was faulty or maybe you tested this on prod https://epfml.github.io/disco? develop still hasn't been merged with prod, I'll do it right now :)

**Comment by Annie-LiGHT** [comment]
whoops--my bad....Thought I was having deja vu 🤤 
(Indeed I saw it in prod)
Thanks!
