### ISSUE TITLE
Windows support of build scripts

### ISSUE THREAD

**Issue by batuhanfaik** [epfml/disco#510]
There is no specific documentation or script for Windows users

**Comment by batuhanfaik** [comment]
Linux/macOS symbolic links do not work with Windows. I will be addressing this soon using `mklink` or CreateSymbolicLink API. See [Windows developer blog](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/)

**Comment by martinjaggi** [comment]
done in #511 and #514
