### ISSUE TITLE
Allowing predictions for trained models

### ISSUE THREAD

**Issue by francesco98** [epfml/disco#519]
Currently Disco allows only to train and validate models, but not to make predictions for already trained models. It would be nice to add the possibility of performing predictions for saved models.

The idea is to add another button to perform predictions for each saved model card in the test section of Disco. In this case, we only need to upload images (or tabular data) without any label.

**Comment by s314cy** [comment]
isn't it a duplicate of #495?

**Comment by francesco98** [comment]
yes, I didn't see it!
