### ISSUE TITLE
task creation form: small details

### ISSUE THREAD

**Issue by martinjaggi** [epfml/disco#523]
for `web-client` -> `TaskCreationForm.vue`

- `List of labels` seems to appear twice?
- `threshold`: i think this has been removed from [TrainingInformation](https://github.com/epfml/disco/blob/develop/discojs/discojs-core/src/task/training_information.ts)
- let's add a title on top of the page for clarity. maybe also very brief intro text on what will happen here

**Comment by s314cy** [comment]
let's also add better feedback on uploading model (.json and .bin) files
