### ISSUE TITLE
upgrade to ES2022

### ISSUE THREAD

**Issue by tharvik** [epfml/disco#632]
currently, we are using EcmaScript 5 (ES5) which is quite old (released in 2009). as the JS ecosystem is moving forward, and quite fast theses years (one new per year), we need to move to a newer version. TypeScript allow uses to use some of theses features by transpiling to older ES via helpers, but it's only partial support, and using theses helpers instead of browser implementations do have size and runtime costs. here goes a list of features that will benefit the project
* async/await support & standard modules (ES6/ES2015)
* async iterator/generator (ES2018)
* `Array.flatMap` (ES2019)
* null coalesing & optional chaining (ES2020)
* `Error.cause` (ES2022)

~94% of browsers [do support ES2022 (except static field block init)](https://caniuse.com/?feats=mdn-javascript_builtins_array_at,mdn-javascript_builtins_regexp_hasindices,mdn-javascript_builtins_object_hasown,mdn-javascript_builtins_error_cause,mdn-javascript_operators_await_top_level,mdn-javascript_classes_private_class_fields,mdn-javascript_classes_private_class_methods,mdn-javascript_classes_static_class_fields), that looks wide enough support to me.

**Comment by peacefulotter** [comment]
I know bun and a bunch of other packages are using esnext. I have heard that it was recommended to set it to esnext but I am not sure about its support coverage
