### ISSUE TITLE
Update module installation doc

### ISSUE THREAD

**Issue by JulienVig** [epfml/disco#635]
The installation instructions are currently outdated, especially now that we are using npm workspaces. 
Update how to install and how to use each module of disco.

- [x] misformatted markdown at the top of DEV.md
- [x] outdated testing instructions in docs/ONBOARDING.md
- [x] outdated VSCode import tip in docs/ONBOARDING.md
- [x] docs/node_example
- [x] web-client/README.md
- [ ] server/README.md
- [x] cli/README.md
- [ ] discojs/README.md
- [ ] discojs/discojs-core/README.md
- [ ] discojs/discojs-node/README.md
- [ ] discojs/discojs-web/README.md
- [ ] Merge server, web-client, discojs installation and usage in DEV.md

**Comment by tharvik** [comment]
arf, I though I updated the doc with the workspaces' PR but indeed, seems like I missed quite a few places, oupsi

**Comment by JulienVig** [comment]
Fixes #609, mostly done after the workspace refactoring.
