### ISSUE TITLE
GPT-tfjs model is not persisted in the browser local storage

### ISSUE THREAD

**Issue by JulienVig** [epfml/disco#800]
Download the GPT model in the Evaluation page doesn't persist the model in the browser's cache: 
- refreshing the page makes it disappear.
- trying to use the model after downloading fails
Inspecting the page, we can see that the local storage (or indexedDB) doesn't show any new model when downloading the GPT model, while it does for others. This happens both in local and for discolab.ai
@tharvik do you have an idea of what's happening? I suspect it may come from #764

**Comment by tharvik** [comment]
after some investigation, it seems that a serialized GPT model is 40MiB which is [way larger than how much we can put in local storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#web_storage). sadly, moving to using a larger storage requires to use async storage which [isn't support by the persist layer we use now](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/limitations.html#storage-must-be-synchronous).

I'm moving to use another persist layer, [`pinia-plugin-persistedstate-2`](https://www.npmjs.com/package/pinia-plugin-persistedstate-2), which allow for async storage. and implementing an [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system) interface.

**Comment by JulienVig** [comment]
I see, not very surprising. This is something we will have to care about as language models grow larger. What about IndexedDB?

**Comment by tharvik** [comment]
IndexedDB is also a possibility. if our case, we don't need to search for data, so OPFS looked more fit.
