### ISSUE TITLE
Tabular columns are not checked anymore before training

### ISSUE THREAD

**Issue by JulienVig** [epfml/disco#801]
Connecting a csv missing some expected columns doesn't trigger the previous error message telling the user that some columns are missing (e.g. trying to train after connecting `titanic_test.csv` instead of `titanic_train.csv`). An error occurs at training time and doesn't specify what is the problem. Additionally the webapp displays "Training successfully completed" even though an error just occurred.
![Screenshot 2024-10-07 at 13 49 53](https://github.com/user-attachments/assets/575cf1fd-f9d9-49fa-a619-f2292c29541b)

@tharvik do you think this was introduced in #682?

**Comment by tharvik** [comment]
ho, yes that's an issue! I think you're right, it was introduced with the rework of loaders; anyway, it is now fixed with the rework of preprocessing in #781
